Create contact me page
Laylooo/Portfolio_1 pull request #3
Opened 2021-06-15 17:17 UTC by Laylooo

2021-06-15 20:47 UTC, Davidosky007 requested changes
Hi @Laylooo, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

 ## Required Changes ♻️
# I left comments below please make necessary changes 🙏 
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- I strongly suggest you fix all broken social icons 
![Screenshot (72)](https://user-images.githubusercontent.com/52497246/122121155-326b4480-ce23-11eb-9365-1c9a1c9a8b0e.png)

![Screenshot (70)](https://user-images.githubusercontent.com/52497246/122121122-28494600-ce23-11eb-80e5-62d9a1a40a78.png)


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2021-06-15 20:47 UTC, Davidosky007 commented on index.html
> +					<button class="button" type="submit">Get in touch</button>
The Button is missing the necessary interactions eg(hover, enable etc.) please fix this as its part of the project requirement

2021-06-15 20:47 UTC, Davidosky007 commented on index.html
> +		</section>
I suggest you stick to the Figma design as much as possible. This is how your contact section looks like, please compare and make the necessary changes 
![Screenshot (73)](https://user-images.githubusercontent.com/52497246/122120610-8a557b80-ce22-11eb-91e5-1a1c304f406b.png)

Figma Design:
![Screenshot (74)](https://user-images.githubusercontent.com/52497246/122120648-95a8a700-ce22-11eb-9b52-00586f01d5fd.png)

2021-06-15 20:55 UTC, Laylooo commented on index.html
> +					<button class="button" type="submit">Get in touch</button>
I made it enabled in the style.css file should I have to do it again or am I doing a mistake. Thanks in advance 😊

2021-06-16 19:51 UTC, Shaher-11 approved these changes
Hello @Laylooo ,

# Congratulations! 🎉 
#### Your project is approved!  There is nothing else to say other than... it's time to merge it :muscle: :muscle: 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Cheers and Happy coding!👏👏👏

2021-06-16 19:54 UTC, merged